sudo: required

services:
  - docker

before_install:
  - docker build -t driesschulten/android .

after_success:
  - docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
  - docker push driesschulten/android

